name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  StyLua:
    name: "Format using StyLua"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check lua/
          version: latest
